version: "3.3"

services:
  db:
    image: mysql:5
    container_name: bdd-dummy-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MYSQL_TCP_PORT=3306
    ports:
      - 3306:3306
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "5m"
